# Generated by Django 3.2.4 on 2021-07-25 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryMan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, default='static/main/images/g3.png', null=True, upload_to='images/laundrymen/')),
                ('header_pic', models.ImageField(blank=True, default='static/main/images/g3.png', null=True, upload_to='images/laundrymen/header/')),
                ('phone_number', models.IntegerField()),
                ('auxiliary_phone_number', models.IntegerField(blank=True, null=True)),
                ('house_number', models.IntegerField()),
                ('street_address', models.TextField(max_length=300)),
                ('area', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=150)),
                ('state', models.TextField(max_length=150)),
                ('about', models.TextField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('dryclean_company', models.BooleanField()),
                ('active', models.BooleanField(default=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('laundry_man', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.IntegerField()),
                ('auxiliary_phone_number', models.IntegerField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='static/main/images/g3.png', null=True, upload_to='images/client/')),
                ('header_pic', models.ImageField(blank=True, default='static/main/images/g3.png', null=True, upload_to='images/client/header/')),
                ('house_number', models.IntegerField()),
                ('street_address', models.TextField(max_length=300)),
                ('area', models.TextField(max_length=300)),
                ('city', models.TextField(max_length=150)),
                ('state', models.TextField(max_length=150)),
                ('about', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
