# Generated by Django 3.2.4 on 2021-07-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iron',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt', models.IntegerField(blank=True, null=True)),
                ('trousers', models.IntegerField(blank=True, null=True)),
                ('suits_and_jackets', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaundryBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_description', models.CharField(choices=[('Weight', 'weight'), ('quantity', 'quantity'), ('dry clean', 'dry clean')], max_length=10)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('shirt', models.IntegerField(blank=True, null=True)),
                ('trousers', models.IntegerField(blank=True, null=True)),
                ('suits_and_jackets', models.IntegerField(blank=True, null=True)),
                ('natives', models.IntegerField(blank=True, null=True)),
                ('underware', models.IntegerField(blank=True, null=True)),
                ('bedsheets', models.IntegerField(blank=True, null=True)),
                ('blankets_and_duvets', models.IntegerField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('iron', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='washapp.iron')),
                ('laundry_man', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.laundryman')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('date_required', models.DateTimeField()),
                ('time_accepted', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('laundry_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='washapp.laundrybasket')),
                ('laundry_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.laundryman')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('laundry_basket', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='washapp.laundrybasket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client')),
            ],
        ),
    ]
